server:
  port: 8083
spring:
  application:
    name: passenger-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/feidichuxing?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root


# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/
